#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_APPLICATION_USER WITH PASSWORD '$POSTGRES_APPLICATION_USER_PASSWORD';
    CREATE DATABASE $POSTGRES_APPLICATION_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_APPLICATION_DATABASE TO $POSTGRES_APPLICATION_USER;
    CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
    CREATE DATABASE $KEYCLOAK_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DATABASE TO $KEYCLOAK_USER;
EOSQL
