<#-- @ftlvariable name="HTML_VARIABLE" type="java.lang.String" -->
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="x-apple-disable-message-reformatting">
    <title></title>
</head>
<body>
<div>
    ${HTML_VARIABLE}
</div>
</body>
</html>