--  REVTYPE
--  ADD – 0 - an INSERT SQL statement has created the entity in question
--  MOD – 1 - an UPDATE SQL statement has modified our entity
--  DEL – 2 - a DELETE SQL statement has removed the audited entity from the database table

CREATE TABLE revinfo
(
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ),
    revtstmp BIGINT,
    PRIMARY KEY (rev)
);

CREATE SEQUENCE hibernate_sequence INCREMENT 1 MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
