CREATE SEQUENCE hibernate_sequence  INCREMENT 1  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

create table job_offer (
    id          bigserial,
    user_id     text,
    title       text,
    mode        text,
    city        text,
    region      text,
    description text
);

create table job_offer_type(
    job_offer_id bigint,
    type text
);

create table job_offer_language (
    job_offer_id bigint,
    language text
);

--  REVTYPE
--  ADD – 0 - an INSERT SQL statement has created the entity in question
--  MOD – 1 - an UPDATE SQL statement has modified our entity
--  DEL – 2 - a DELETE SQL statement has removed the audited entity from the database table

CREATE TABLE revinfo
(
    rev      INTEGER GENERATED BY DEFAULT
             AS IDENTITY ( START WITH 1 ),
    revtstmp BIGINT,
    PRIMARY KEY ( rev )

);

create table job_offer_language_AUD (
    job_offer_id bigint,
    language text,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    REVEND      INTEGER,
    PRIMARY KEY ( language, REV ),
    CONSTRAINT FK_job_offer_language_AUD_REV
        FOREIGN KEY(rev)
            REFERENCES revinfo(rev),
    CONSTRAINT FK_job_offer_language_AUD_REVEND
        FOREIGN KEY(revend)
            REFERENCES revinfo(rev)
);

create table job_offer_type_AUD (
    job_offer_id bigint,
    type text,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    REVEND      INTEGER,
    PRIMARY KEY ( type, REV ),
    CONSTRAINT FK_job_offer_type_AUD_REV
        FOREIGN KEY(rev)
            REFERENCES revinfo(rev),
    CONSTRAINT FK_job_offer_type_AUD_REVEND
        FOREIGN KEY(revend)
            REFERENCES revinfo(rev)
);

CREATE TABLE job_offer_AUD
(
    id          bigserial,
    user_id     text,
    title       text,
    mode        text,
    city        text,
    region      text,
    description text,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    REVEND      INTEGER,
    PRIMARY KEY ( id, REV ),
    CONSTRAINT FK_job_offer_AUD_REV
        FOREIGN KEY(rev)
    	    REFERENCES revinfo(rev),
    CONSTRAINT FK_job_offer_AUD_REVEND
        FOREIGN KEY(revend)
            REFERENCES revinfo(rev)
);

