name: Publish package as Github release

on:
  release:
    types: [created]

jobs:
  release-github-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Set version from git tag
        run: ./gradlew build -x test -P version=${{ env.TAG }}

      - name: Add jar to Github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/ogloszenia-${{ env.TAG }}.jar
          asset_name: ogloszenia-${{ env.TAG }}.jar
          tag: ${{ github.ref }}
